export const data = [
  {
    link: "course",
    tab: "популярное",
    img: "/images/card-img2.png",
    title: "Porem ipsum dolor",
    day: "06",
    month: "февраля",
    desc: "Morem ipsum dolor sit amet, consectetur",
  },
  {
    link: "course",
    tab: "популярное",
    img: "/images/card-img3.png",
    title: "Porem ipsum dolor",
    day: "06",
    month: "февраля",
    desc: "Morem ipsum dolor sit amet, consectetur",
  },
  {
    link: "course",
    tab: "популярное",
    img: "/images/card-img4.png",
    title: "Porem ipsum dolor",
    day: "06",
    month: "февраля",
    desc: "Morem ipsum dolor sit amet, consectetur",
  },
  {
    link: "course",
    tab: "популярное",
    img: "/images/card-img2.png",
    title: "Porem ipsum dolor",
    day: "06",
    month: "февраля",
    desc: "Morem ipsum dolor sit amet, consectetur",
  },
  {
    link: "course",
    tab: "популярное",
    img: "/images/card-img3.png",
    title: "Porem ipsum dolor",
    day: "06",
    month: "февраля",
    desc: "Morem ipsum dolor sit amet, consectetur",
  },
  {
    link: "course",
    tab: "популярное",
    img: "/images/card-img1.png",
    title: "Porem ipsum dolor",
    day: "06",
    month: "февраля",
    desc: "Morem ipsum dolor sit amet, consectetur",
  },
  {
    link: "course",
    tab: "популярное",
    img: "/images/card-img1.png",
    title: "Porem ipsum dolor",
    day: "06",
    month: "февраля",
    desc: "Morem ipsum dolor sit amet, consectetur",
  },
  {
    link: "course",
    tab: "уроки",
    img: "/images/card-img1.png",
    title: "Porem ipsum dolor",
    day: "06",
    month: "февраля",
    desc: "Morem ipsum dolor sit amet, consectetur",
  },
  {
    link: "course",
    tab: "уроки",
    img: "/images/card-img2.png",
    title: "Porem ipsum dolor",
    day: "06",
    month: "февраля",
    desc: "Morem ipsum dolor sit amet, consectetur",
  },
  {
    link: "course",
    tab: "уроки",
    img: "/images/card-img1.png",
    title: "Porem ipsum dolor",
    day: "06",
    month: "февраля",
    desc: "Morem ipsum dolor sit amet, consectetur",
  },
  {
    link: "course",
    tab: "КУРСЫ",
    img: "/images/card-img4.png",
    title: "Porem ipsum dolor",
    day: "06",
    month: "февраля",
    desc: "Morem ipsum dolor sit amet, consectetur",
  },
  {
    link: "course",
    tab: "КУРСЫ",
    img: "/images/card-img1.png",
    title: "Porem ipsum dolor",
    day: "06",
    month: "февраля",
    desc: "Morem ipsum dolor sit amet, consectetur",
  },
  {
    link: "course",
    tab: "КУРСЫ",
    img: "/images/card-img1.png",
    title: "Porem ipsum dolor",
    day: "06",
    month: "февраля",
    desc: "Morem ipsum dolor sit amet, consectetur",
  },
];
